// SchedulerCenter.idl : SchedulerCenter 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(SchedulerCenter.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(D812B084-D25B-4C8F-805E-0265F5E04CD3),
	version(1.0),
]
library SchedulerCenterLib
{
	importlib("stdole2.tlb");
};

