PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;


CREATE TABLE [T_Para] (
	ParaName VARCHAR DEFAULT '' NOT NULL PRIMARY KEY UNIQUE,
	ParaValue VARCHAR DEFAULT '' NOT NULL);
INSERT INTO T_Para VALUES('DBVersion','3900');

COMMIT;
