// HostService.idl : HostService 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(HostService.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E99D4D05-FCF2-456F-A177-D030453C94F8),
	version(1.0),
]
library HostServiceLib
{
	importlib("stdole2.tlb");
};

